### ISSUE TITLE
Include :vimgrep command to search in multiple files

### ISSUE THREAD

**Issue by cnlopes** [rtorr/vim-cheat-sheet#126]
Searching for a term in multiple files within the project is a very useful feature, especially when we need to refactor code.

The syntax for the `:vimgrep` command as well as `:cn`, `:cp` and `:copen` could be included in the cheat sheet, to provide instruction about how to search and navigate the results.

**Comment by rtorr** [comment]
@cnlopes I agree! Would you be willing to submit a pull request?

**Comment by cnlopes** [comment]
@rtorr yes, I'll submit a pull request soon.
