### ISSUE TITLE
Suggestion for include 1p and 1P

### ISSUE THREAD

**Issue by sijad** [rtorr/vim-cheat-sheet#166]
`1p` put (paste) in next new line
`1P` put (paste) in above new line

**Comment by Melkor333** [comment]
This is the same as `p` and `P`, which is already included. It does only paste on newline, if a full line as already been copied (with something like `yy`).

But what could be added is `*p` / `*P`, whereas * stands for any number. Doing `2p` would paste the buffer **twice after** cursor, `3P` would paste it **three times before** the cursor.
I would like to change the already existing `p` and `P` to something like `[letter +] p` and `[letter +] P`. But for this, I will have to realise #33 (I want to do this as soon as I find some time, but I want to do it cleanly, which may take a while).

**Comment by rtorr** [comment]
Its been a while, so closing. Re-open if you have questions or want to submit a PR.
