### ISSUE TITLE
"0p - paste contents of register x

### ISSUE THREAD

**Issue by adrianN** [rtorr/vim-cheat-sheet#172]
I think it should be `"xp`, but I don't know which part of the repository to change, so I can't do a pull request.

**Comment by tkraak** [comment]
@adrianN ... I believe that `"0p` is supposed to illustrate the point that register 0 always contains the value of the last yank command.

**Comment by tkraak** [comment]
How about we clarify / enhance / resolve it like like this:

`"xy` - yank into register x
`"xp` - paste contents of register x
`"0p` - paste contents of last yank

**Comment by adrianN** [comment]
I think that would be good.

**Comment by rtorr** [comment]
Make a PR 👍

**Comment by adrianN** [comment]
"0p has been deleted by 5bc3cd78adde020c37364d2f2e07378262240dd6
