### ISSUE TITLE
Confusion between O and 0

### ISSUE THREAD

**Issue by s-rajaraman** [rtorr/vim-cheat-sheet#194]
I started using the website as I learn how to use vim. I keep getting confused on whether the hotkey is O or 0. A different font might help; a zero will have a slash or dot in the middle. O will just be a circle.

[Example Font](https://fonts.google.com/specimen/Inconsolata) 

This could just be my problem; but there is a chance other users go through this as well.

**Comment by rtorr** [comment]
Open to a PR :D

**Comment by rtorr** [comment]
The only reason I havent done this is because the cheat sheet is currently using system fonts. This is for speed and simplicity.

**Comment by rtorr** [comment]
Its been added https://github.com/rtorr/vim-cheat-sheet/commit/e5dfeae74a13706920272c1293fa6a95e68149c3
