### ISSUE TITLE
Add "semicolon" and "comma" commands

### ISSUE THREAD

**Issue by stfacc** [rtorr/vim-cheat-sheet#210]
It would be useful to add the ; (semicolon) and , (comma) commands, which respectively repeat the last f, F, t or T movement, or repeat it backwards. Thanks.

**Comment by rtorr** [comment]
Pull requests welcome 😃

**Comment by glhrmv** [comment]
This already looks to be present in the [`config.yaml` file](https://github.com/rtorr/vim-cheat-sheet/blob/master/_config.yml#L46-L51) and in the [`_layouts/page.html` file](https://github.com/rtorr/vim-cheat-sheet/blob/master/_layouts/page.html#L41-L47). But it is not present in the live version of the site. Shouldn't this issue be closed?
