### ISSUE TITLE
Printer Friendly Design

### ISSUE THREAD

**Issue by rupertdev** [rtorr/vim-cheat-sheet#221]
I'd love to print out this page and stick on the wall in front of my desk. It'd be great to have a nice printer friendly version of the page.

**Comment by rtorr** [comment]
Once upon a time it was very printer friendly. PRs welcome. :D

**Comment by rtorr** [comment]
https://github.com/rtorr/vim-cheat-sheet/blob/master/_includes/styles.scss#L191

**Comment by k1-hedayati** [comment]
I came here to create an issue about print friendly version and I saw it's already created, I liked this cheat sheet over others but unfortunately it is not easy to print.

**Comment by rtorr** [comment]
Definitely interested in pull requests! Over time when new additions made it look worse.

**Comment by sin** [comment]
Hi, a few months ago I've created a printer friendly version, but I can't make a pull request because it's not screen friendly anymore. 😄 

[Here's ready to print PDF version (one page, horizontal).](https://github.com/sin/vim-cheat-sheet/blob/master/vim-cheat-sheet.pdf)

**Comment by rtorr** [comment]
It might be time for me to tackle this issue again

**Comment by sebma** [comment]
@sin Nice pdf. What did you use to convert the cheatsheet to pdf ?

**Comment by rtorr** [comment]
@sin maybe we can make a new route with this print friendly version?
