### ISSUE TITLE
Page navigation commands not rendered

### ISSUE THREAD

**Issue by dougal** [rtorr/vim-cheat-sheet#253]
I noticed that the descriptions for `ctrl + f/d/u` are not being rendered.

Same issue in every language. I can't see an obvious issue with the template that would cause this. Happens when checked out and run locally.

![Screenshot 2019-04-06 at 12 32 18](https://user-images.githubusercontent.com/1256/55668924-7e47f980-5868-11e9-9620-71f8792b071c.png)
![Screenshot 2019-04-06 at 12 32 06](https://user-images.githubusercontent.com/1256/55668925-7ee09000-5868-11e9-8bee-90e5c8ff5540.png)

Thanks for the cheatsheet, printing it out and being able to write on it was a huge help to me in my first few days.

**Comment by rtorr** [comment]
They need to escaped probably, I’ll look into a fix

**Comment by rtorr** [comment]
fixed
