### ISSUE TITLE
Command descriptions are missing

### ISSUE THREAD

**Issue by jkaichang** [rtorr/vim-cheat-sheet#260]
I noticed that queries for `ctrl + f/d/u` are missing in `src/templates/sheet.js`. This seems to cause a bug similar to #253, command descriptions are missing for pages under
`vim.rtorr.com/lang/`.

**Comment by rtorr** [comment]
PR welcome!

**Comment by jkaichang** [comment]
Just opened a PR.

**Comment by rtorr** [comment]
Awesome, thanks!
