### ISSUE TITLE
Consider adding gj and gk commands

### ISSUE THREAD

**Issue by Julioevm** [rtorr/vim-cheat-sheet#263]
In the cursor movement section, consider adding "gj" and "gk" to visually move down and up respectively.
Thanks!

**Comment by dwettstein** [comment]
Hi @Julioevm 

<kbd>gj</kbd> and <kbd>gk</kbd> only differs from <kbd>j</kbd> and <kbd>k</kbd> when the line wraps, but in certain cases it can be useful.

> gk    N  gk           up N screen lines (differs from "k" when line wraps)
> gj    N  gj           down N screen lines (differs from "j" when line wraps)
> Reference: https://vimhelp.org/motion.txt.html#up-down-motions

Cheers!

**Comment by rtorr** [comment]
Yeah I’m not sure about adding these. If you feel strongly, try a PR.
