### ISSUE TITLE
consider adding `zt` and `zb`

### ISSUE THREAD

**Issue by smjure** [rtorr/vim-cheat-sheet#317]
There's already `zz`, which position current line in the center of a page. Similarly, `zt` and `zb` position current line to the top or bottom respectively.

**Comment by rtorr** [comment]
Open to PRs!

**Comment by wenfangdu** [comment]
This should be reopened 🥺.

**Comment by rtorr** [comment]
@wenfangdu want to make a pr? I will reopen.

**Comment by Endermanbugzjfc** [comment]
I would suggest `gv` (re-select previous selected texts) as well.

**Comment by wenfangdu** [comment]
`zt` and `zb` have been added:
![image](https://github.com/rtorr/vim-cheat-sheet/assets/28700378/7bbbb7d0-4dfc-4d8f-afc5-703f233c9cc0)
