### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by mjdr** [rtorr/vim-cheat-sheet#328]
Everything needs a dark theme.
And it`s couple lines of css and js

**Comment by ledinscak** [comment]
If you want to test dark theme just use Dark Reader in
 - firefox: https://addons.mozilla.org/nb-NO/firefox/addon/darkreader/ or 
 - chrome: https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en

But yeah +1

**Comment by rtorr** [comment]
im a +1 too. Let me think about how i want to go about this.

**Comment by PabloEmidio** [comment]
Hey! Is there any update about this development? I am working with the cheatsheet opened all day long and really could use a dark mode.
