### ISSUE TITLE
Arabic translation isn't complete

### ISSUE THREAD

**Issue by AhmedIbrahim336** [rtorr/vim-cheat-sheet#353]
I checked the Arabic translation and it is not complete. Are you okay with me submitting a PR to replace the missing stuff?
<details>
   <summary>Screenshot</summary>

![arabic](https://user-images.githubusercontent.com/72753578/189516672-30f76526-7230-4fb9-8550-acf1d0ff64db.png)

</details>

**Comment by AhmedIbrahim336** [comment]
@rtorr Just want to confirm is this project still accepting new PRs.

**Comment by rtorr** [comment]
It is, and I am very happy to review your PR.

**Comment by AhmedIbrahim336** [comment]
Thanks, @rtorr! I try to get done with it this week!

**Comment by AhmedIbrahim336** [comment]
#357

**Comment by AhmedIbrahim336** [comment]
The Arabic version of the website is now available 🎉
