### ISSUE TITLE
The French cheat sheet is not complete.

### ISSUE THREAD

**Issue by ave6** [rtorr/vim-cheat-sheet#54]
Two commands in the French sheet are still in English (Ctrl + wh and Ctrl + wl).
![The issue](http://i.imgur.com/G3pO6Ol.png "The Issue")
This is only a minor issue that I found, but the fixes would be: 
 * Ctrl + wh: déplacer le curseur vers le prochain tampon.
 * Ctrl + wl: déplacer le curseur vers le tampon précédent.

**Comment by rtorr** [comment]
@ave6 I welcome a pull request :) or I can get to it soon
