### ISSUE TITLE
There is no favicon

### ISSUE THREAD

**Issue by Agares** [rtorr/vim-cheat-sheet#64]
Hi!
I've just noticed that the wonderful Vim Cheatsheet has no favicon. It's a little annoying, when I have a tab with it pinned in my browser. As far as I know, vim's icon is GPL-licensed, so it can't be used in MIT-licensed project (please correct me if I am wrong). But there is, for example vim-replacement-icon (https://github.com/jasonlong/vim-replacement-icon) available, which should be fine.

**Comment by rtorr** [comment]
@Agares awesome idea! I will try and add it soon. Thanks.

**Comment by rtorr** [comment]
favicon has been added here https://github.com/rtorr/vim-cheat-sheet/pull/65

**Comment by rtorr** [comment]
pinging @jasonlong to let him know its been added to this project :)

**Comment by jasonlong** [comment]
:metal: Nice!

**Comment by Agares** [comment]
Thank you! That is great :)
