### ISSUE TITLE
suggest a 'write read-only file' command

### ISSUE THREAD

**Issue by cuter44** [rtorr/vim-cheat-sheet#75]
Though not a basic command, but `:w !sudo tee %` is quite useful on Ubuntu.  
Also some pseudo-commands are important but a hidden trick to newbie, such as 'enable line-no', 'enable syntax-highlight', 'change file type'... Maybe a new section is needed to include them.  
Just depends on you. ╮(‾▽‾)╭

**Comment by rtorr** [comment]
I'm open to new suggestions, and welcome pull requests if you flush that idea out

**Comment by cascer1** [comment]
Wouldn't `:w!` also write a read-only file?

**Comment by cuter44** [comment]
@cascer1 `:w!` works only you are the owner of file, `:w !sudo tee %` always works if you are a sudoer. As I just tested.
So these two may be using in different scenario, I think.
Anyway, thank you. You enlightened me. ("ㅍ‿ㅍ)
