### ISSUE TITLE
Suggestions for inclusion: f and t; text-object motions and the very-magic switch

### ISSUE THREAD

**Issue by matatk** [rtorr/vim-cheat-sheet#81]
I'm a bit of a newbie at Vim (though I've been using it for about 11 years on-and-off).  I've been following http://vimcasts.org and want to learn to navigate text as effectively as is done in that video series (i.e. not taking my hands off the keyboard, and navigating via motions as much as possible), hence this cheat sheet is very helpful; thank you.

From watching the pros do it, it seems that a few useful commands to add to the cheat sheet might be these…
- [f and t](http://stackoverflow.com/questions/12495442/what-do-the-f-and-t-commands-do-in-vim)
- [text object motions](http://vimdoc.sourceforge.net/htmldoc/motion.html#}) (e.g. to move to the next } or paragraph)
- [the very-magic switch on search patterns](http://vimdoc.sourceforge.net/htmldoc/pattern.html#/v) to make them behave like 'normal' (UNIX/Perl/de-facto) regexes.

Though I know that deciding what's 'in' and what's 'out' mustn't be easy, I feel that these would help me keep my hands on the keyboard (and also not just falling back to using the hjkl 'arrow' keys).

I'd be happy to have a go at making a patch to include these, if you feel they should be included.

**Comment by rtorr** [comment]
@matatk I am always open to making this document better. As a goal, this document is not trying to be a list of everything possible with vim, but rather be short and concise. That being said, if you make a pull request that will add these new commands in a way that can fit in, I will gladly merge it!

Thanks for the suggestion :D
