### ISSUE TITLE
Suggestion: Printer friendly version

### ISSUE THREAD

**Issue by matt-snider** [rtorr/vim-cheat-sheet#85]
Firstly, this is a great cheat sheet! Thanks!

I tried to print it so I can keep it on my desk, but it's not very printer friendly so it all gets shoved into a single six page long column. What do you think of a printer friendly version?

**Comment by rtorr** [comment]
@matt-snider its been something I've wanted to get to for a very long time. You can take a stab at it, or I can put it on my TODO list.

**Comment by matt-snider** [comment]
@rtorr Sounds good. I could definitely give it a shot

**Comment by rtorr** [comment]
cc @matt-snider 

https://github.com/rtorr/vim-cheat-sheet/pull/92

**Comment by matt-snider** [comment]
Thanks for the heads up!
