### ISSUE TITLE
Removing search match highlighting

### ISSUE THREAD

**Issue by talbotja** [rtorr/vim-cheat-sheet#98]
I really like the cheatsheet, it's saved me loads of time while getting to know vim.

One thing I did still have to google though was how to remove the highlighting of matches following a search. The easiest answer seems to be to use :noh - is this something you would consider worth adding to the cheatsheet, presumably under the 'Search and replace' section? I'm happy to make the changes myself if you're accepting PRs.

**Comment by rtorr** [comment]
Yep, send over a pull request :D
